apiVersion: v1
kind: ConfigMap
metadata:
  name: ascendly-config
  namespace: {{ .Values.namespace }}
data:
  ENVIRONMENT: {{ .Values.config.ENVIRONMENT | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  FRONTEND_URL: {{ .Values.config.FRONTEND_URL | quote }}
  API_BASE_URL: {{ .Values.config.API_BASE_URL | quote }}
  MONGODB_URI: {{ .Values.config.MONGODB_URI | quote }}
  REDIS_URL: {{ .Values.config.REDIS_URL | quote }}
  MEILI_URL: {{ .Values.config.MEILI_URL | quote }}
  MEILI_MASTER_KEY: {{ .Values.config.MEILI_MASTER_KEY | quote }}
