namespace: ascendly
image:
  repository: ascendly-api
  tag: latest
  pullPolicy: IfNotPresent
replicas: 2
serviceAccountName: ascendly-platform
configMapRef: ascendly-config
secretRef: ascendly-secrets
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTarget: 70
  memoryTarget: 80
  scaleUpStabilizationSeconds: 60
  scaleUpPercent: 100
  scaleUpMaxPods: 4
  scaleDownStabilizationSeconds: 300
  scaleDownPercent: 50
ingress:
  enabled: true
  host: ascendly.io
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
