apiVersion: v1
kind: Service
metadata:
  name: ascendly-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: ascendly-api
  ports:
    - port: 8000
      targetPort: 8000
