import json
import logging
import time

from fastapi import FastAPI, Response
from prometheus_client import (
    CONTENT_TYPE_LATEST,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)
from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.requests import Request
from starlette.responses import Response as StarletteResponse

from app.core.context import get_request_id

REQUEST_COUNT = Counter(
    "http_requests_total",
    "Total HTTP requests by method, path, and status",
    ["method", "path", "status"],
)

REQUEST_DURATION = Histogram(
    "http_request_duration_seconds",
    "HTTP request duration in seconds",
    ["method", "path"],
    buckets=[0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
)

WORKER_QUEUE_DEPTH = Gauge("worker_queue_depth", "Current number of jobs in the queue")
WORKER_DLQ_COUNT = Gauge("worker_dlq_count", "Current number of jobs in the dead-letter queue")
WORKER_JOBS_ENQUEUED = Counter("worker_jobs_enqueued_total", "Total jobs enqueued", ["task"])
WORKER_JOBS_COMPLETED = Counter("worker_jobs_completed_total", "Total jobs completed", ["task", "status"])

# LLM metrics (consumed by AI-B's Phase 2 alerts).
LLM_REQUESTS = Counter(
    "llm_requests_total",
    "Total LLM requests by provider and status (success/error)",
    ["provider", "status"],
)
LLM_TOKENS = Counter(
    "llm_tokens_total",
    "Total LLM tokens (estimated) by provider",
    ["provider"],
)
# Note: prometheus_client appends `_total` to Counter names automatically, so
# the base name here (`llm_cost_usd`) is exposed on /metrics as
# `llm_cost_usd_total{provider}`. Alert/dashboard queries must use the
# `_total`-suffixed series name.
LLM_COST_USD = Counter(
    "llm_cost_usd",
    "Estimated LLM cost in USD by provider",
    ["provider"],
)

# ── Adaptive Learning metrics (Phase 5 contract M1–M5) ──────────────────────
# Metric names are frozen in AI_PROMPTS/phase5/WORK_DIVISION_PHASE5.md §4 for
# AI-B's dashboards/alerts — do not rename without Supervisor sign-off.
ADAPTIVE_QUIZ_GENERATED = Counter(
    "adaptive_quiz_generated_total",
    "Adaptive quizzes generated by mode and course",
    ["mode", "course_id"],
)
ADAPTIVE_QUIZ_SUBMITTED = Counter(
    "adaptive_quiz_submitted_total",
    "Adaptive quiz submissions by mode and pass status",
    ["mode", "passed"],
)
ADAPTIVE_QUIZ_SUBMIT_DURATION = Histogram(
    "adaptive_quiz_submit_duration_seconds",
    "Adaptive quiz grading (submit) duration in seconds by course",
    ["course_id"],
    buckets=[0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
)
ADAPTIVE_MASTERY_DECAY_RUNS = Counter(
    "adaptive_mastery_decay_runs_total",
    "Mastery decay cron runs by status (success/failed)",
    ["status"],
)
ADAPTIVE_REMEDIATION_GENERATED = Counter(
    "adaptive_remediation_generated_total",
    "Remedial content generations by concept",
    ["concept_id"],
)
# Phase 6 (NV4) contract M6/M7 — added on top of M1–M5, names frozen for AI-B.
ADAPTIVE_REMEDIATION_FEEDBACK = Counter(
    "adaptive_remediation_feedback_total",
    "Remedial content feedback by helpfulness",
    ["helpful"],
)
ADAPTIVE_REMEDIATION_EXERCISE_SUBMITTED = Counter(
    "adaptive_remediation_exercise_submitted_total",
    "Remedial exercise submissions by concept and pass status",
    ["concept_id", "passed"],
)

# Phase 7 (NV5) contract M8 — added on top of M1–M7, name frozen for AI-B
# (alerts/dashboards). `prometheus_client` appends `_total` to Counter names.
INTELLIGENCE_SNAPSHOT_RUNS = Counter(
    "intelligence_snapshot_runs",
    "Intelligence snapshot runs by status (success/live_fallback/failed)",
    ["status"],
)

# Phase 7 (NV5) contract M9 — retention cron outcome by collection+status,
# consumed by AI-B's retention job (app/core/tasks.py::run_retention_cleanup).
RETENTION_CLEANUP_RUNS = Counter(
    "retention_cleanup_runs",
    "Retention cleanup runs by collection and status (success/skipped/error)",
    ["collection", "status"],
)


class TelemetryMiddleware(BaseHTTPMiddleware):
    async def dispatch(
        self, request: Request, call_next: RequestResponseEndpoint
    ) -> StarletteResponse:
        start = time.monotonic()
        response = await call_next(request)
        duration = time.monotonic() - start

        method = request.method
        path = request.url.path
        status = response.status_code

        REQUEST_COUNT.labels(method=method, path=path, status=status).inc()
        REQUEST_DURATION.labels(method=method, path=path).observe(duration)

        logger = logging.getLogger("access")
        logger.info(
            "%s %s %d %.2fms",
            method,
            path,
            status,
            duration * 1000,
            extra={
                "method": method,
                "path": path,
                "status": status,
                "duration_ms": round(duration * 1000, 2),
                "client_ip": request.client.host if request.client else None,
                "user_agent": request.headers.get("user-agent"),
                "request_id": get_request_id(),
            },
        )

        # Log 5xx responses as errors to error logger
        if status >= 500:
            try:
                import asyncio

                from app.core.error_logger import (
                    CATEGORY_HTTP,
                    LEVEL_ERROR,
                    SOURCE_BACKEND,
                    get_error_logger,
                )
                # Fire-and-forget: don't await to avoid blocking response
                asyncio.create_task(get_error_logger().log(
                    source=SOURCE_BACKEND,
                    level=LEVEL_ERROR,
                    category=CATEGORY_HTTP,
                    error_type="HTTP5xx",
                    message=f"HTTP {status} error",
                    url=path,
                    method=method,
                    status_code=status,
                    ip_address=request.client.host if request.client else None,
                    user_agent=request.headers.get("user-agent"),
                    request_id=get_request_id(),
                ))
            except Exception:
                # Don't let logging errors break the response
                pass

        return response


def configure_logging(environment: str = "development") -> None:
    access_logger = logging.getLogger("access")

    if access_logger.handlers:
        return

    handler = logging.StreamHandler()
    handler.setLevel(logging.INFO)

    if environment == "production":
        class JSONFormatter(logging.Formatter):
            def format(self, record: logging.LogRecord) -> str:
                obj = {
                    "timestamp": self.formatTime(record),
                    "level": record.levelname,
                    "logger": record.name,
                    "message": record.getMessage(),
                    "module": record.module,
                    "function": record.funcName,
                    "line": record.lineno,
                }
                if hasattr(record, "extra") and record.extra:
                    obj.update(record.extra)
                return json.dumps(obj)

        formatter = JSONFormatter()
    else:
        formatter = logging.Formatter(
            "%(asctime)s [%(levelname)s] %(message)s"
        )

    handler.setFormatter(formatter)
    access_logger.addHandler(handler)
    access_logger.setLevel(logging.INFO)

    root = logging.getLogger()
    if not root.handlers:
        root.addHandler(handler)
        root.setLevel(logging.INFO)


def setup_telemetry(app: FastAPI, environment: str = "development") -> None:
    configure_logging(environment)

    @app.get("/metrics")
    async def metrics():
        return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)

    app.add_middleware(TelemetryMiddleware)


def start_metrics_server(port: int = 9101) -> None:
    """Start a micro Prometheus HTTP server (GET /metrics) in a daemon thread.

    Used by the worker/cron processes which don't run FastAPI — Prometheus
    scrapes the API on :8000 and the worker/cron on :9101 (override with
    PROMETHEUS_PORT). Shares the default registry with the API process so all
    counters (http_*, worker_*, llm_*) are exposed.
    """
    from prometheus_client import start_http_server

    try:
        start_http_server(port)
        logging.getLogger(__name__).info("Prometheus metrics server listening on :%d/metrics", port)
    except OSError as exc:
        logging.getLogger(__name__).warning(
            "Prometheus metrics server on :%d failed to start (already bound?): %s", port, exc
        )