apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace }}
    app.kubernetes.io/part-of: ascendly
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: ascendly
automountServiceAccountToken: false
