apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ascendly-api-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.pdb.apiMinAvailable }}
  selector:
    matchLabels:
      app: ascendly-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ascendly-worker-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.pdb.workerMinAvailable }}
  selector:
    matchLabels:
      app: ascendly-worker
