#ENC[AES256_GCM,data:Rv7F2uO7TaJf7/HiQ+iMFWRj88hRKR/BTZ7SBSra1MCG4NtI4hgkt6BM0esGC7ffSuGM5auXntaOtVFZ/b7RNYz6QBXd/og6MtJ4aWxq,iv:SE06TtfMw2TEjh+w9DBiYoYvogyPfRvFMwW9ntSSNR0=,tag:GTTXYPLTLLMFt+Q1rwwVig==,type:comment]
#ENC[AES256_GCM,data:sh5/hOqMAG6rnst9rRTwzHdFzsJJZGmHaBa4Eh3g339szX5uiJohX0vWvnaZJ16BTDNSwDNQYGsUQKJI0LxHvY/CsyehpqsG3Jlm,iv:o12+EiULpWTd6fJilKZPJdDpkr5JfFosYhxXCDrjsug=,tag:WyzVpF/8XC0A3aaSlH1iNA==,type:comment]
#ENC[AES256_GCM,data:gqCV1pNYRb5X0LmERFnOzbX5oeIBV13Qc90TxWO/JyrAi9bYj90rpvXf6DvjTdZqVKodeJ6H1JqfKf9i,iv:yStQWGrXffl3aq0NYTnWCTE0pcWR+lgGlfWLLhQKWhU=,tag:zEjtKdpTSfKQrSaxgO5YIA==,type:comment]
apiVersion: ENC[AES256_GCM,data:NtY=,iv:7VUZ3TlB95ZwGhRKJooKb3RwuSsnoBgTwtpSb8nH4TQ=,tag:6c8SydoiWKyS8XeupsqQzg==,type:str]
kind: ENC[AES256_GCM,data:W+SYpv1N,iv:PmEhmUIA9j1qGbCE9wZI+YJSMyN8HrhSUg9wmRxsRqs=,tag:m/qLZn7HgvA+IQEo9Ve+Kw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0I5orMfqkM/Z4NYg8Z2qTQ==,iv:4UUK8tQsiHsDln1SsolDJaWG+hiHiO108j9H+4jBo08=,tag:165qWTSVS1hp8Yh++slWrg==,type:str]
    namespace: ENC[AES256_GCM,data:4SRVlTyAQuU=,iv:ZvMEV70ciuzSX9Yf3WO0jgB0VROTjoT7pOPVizHCPF0=,tag:tTHcdVP5ieGvlyVnzfORMg==,type:str]
type: ENC[AES256_GCM,data:0bFRx3c4,iv:6mFmyGZW1k+UIZLIlf3KSzoScZkaiJAXHgHNb2ORiXI=,tag:J8gxU4lJypWUVue/XAYXaQ==,type:str]
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:N4xRbcBOFJTzAersS64Vc7xao4UOa6Ep,iv:Z8Q6Xbg39n7mgZp7sPYpsS+zmBCNRoghv/EsKfgtRZM=,tag:d8HmEBpSNBm/0PD7IHtXoA==,type:str]
    R2_ACCESS_KEY_ID: ""
    R2_SECRET_ACCESS_KEY: ""
    OPENAI_API_KEY: ""
    OPENROUTER_API_KEY: ""
    GEMINI_API_KEY: ""
    TAVILY_API_KEY: ""
    SMTP_USER: ""
    SMTP_PASSWORD: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cn2x22y4xn5jflxe6539ujtc52m38tyjyfnv4nygva4wym7975kskt4smr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dk5EaFVqWkY2U1VTbyts
            QzUvbTZFZk5nY2d1OStuVnd1M3AxRTBkWVF3Clk3ZnZWc1BaNWtRU2lBRnNPeEpK
            YndBNUdiaUVzYVVGTFp0TFJrSitKUGcKLS0tIDhveXltdU5ZZkNtak5BaE9UTXpL
            RzV1K3dYOVd6K1hzNisvTCtRS0RGL28K+5eUNfGeyyR1pIxMdkRJQb6J/Dm6xFBe
            eYmGZwxOI+s5+1QE4ITQi72V/ayVkOrF+mg4Vgb0sGI9uaAaPJN7zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T12:17:44Z"
    mac: ENC[AES256_GCM,data:2IFMOG359gIrlGOCuOnEkKSaN3JMM9uS+VOW14808PNeKzXbsdmXgm3nHzG8a+Fixp0/+SdiIU7c9J5sn8bfHlzK3GOVTFp1aCg7RcMnDXWYK5iz+PTDuSNq1P1IqDH584mEvjdOrd2NOr6aLTy49Y/fkvxmy5BcNsmVBMPmoeI=,iv:UerXV1cX5WlPZ955SP8MBeETRQeItVy49A3Z8tydCJU=,tag:RJJHQbPU0M7bUIqRHOipoQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
