#ENC[AES256_GCM,data:OcUdCr7HE9JpaJWAOmq8IHd1pCwHLqfGfXf9ohiX8qPgcA5VJCoMGEWFJZBMK8nNZ5b1KMqVH+BTv4t0qGEPTwULObZBJGon2TcUiMmX,iv:NoRgv3MmzphW7ZEyFO/CHDuIY6YQUK1JpbveYm63njQ=,tag:+dTEuu8s74i+4sY0zQHKtA==,type:comment]
#ENC[AES256_GCM,data:l1t/VPhI6RE7TW8HMzaKEsstnE+ASClzeClNx6obssMbw4/ZKm91iRCCMAr4PDfcn1DCzbkHam0oxfRfm7C7ebVCIHNw9jOOyxXJyRc=,iv:5DCrJNKO7ihQ6Qqre1WXboiGrGlrt5G7tiB9E0V4kuM=,tag:kep77iQ00zDJNM3whIXh7w==,type:comment]
#ENC[AES256_GCM,data:+XniiiCie5gFA8r2iBLufKhZWAbTNG6wujiXhLvVzzIVjOmQlMZjEHaueXYijhT7XPakcg==,iv:P5HkImgr7K43TdfLLO87/WceqKG+BmBX/MhHeZvAil0=,tag:51EkjGYg+mOiPYFAxnOk6w==,type:comment]
apiVersion: ENC[AES256_GCM,data:7pk=,iv:hNp5aLEu8XjHyzYJmqV7L60kHGYAjI9nIl0X5lEalBQ=,tag:BfCG54EBtpZ7FUDhwJqFvg==,type:str]
kind: ENC[AES256_GCM,data:wOoWsr2b,iv:wzx62iMGP+B4cC2zuNIhXFCN/WrZf+r4rpHJS3/B0dY=,tag:p2DObcor3eCt8XFeFl8sVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3n1FEhuMiVufmLaQr0AiWQ==,iv:osr8B3+8xe3jDhzDceVYvw4IHZ5uynjek3OBQTJN2Fw=,tag:bvnTbP44KdB/n/xOoPerfw==,type:str]
    namespace: ENC[AES256_GCM,data:UOY5GB01Q+3/eYa2b4bymg==,iv:tf4Ld2fg4v5sDNLb+nADWe/dRZeHIxNvFMbhc6xT8vQ=,tag:BJlu534Drpq4CF4l0ZZVHA==,type:str]
type: ENC[AES256_GCM,data:Oz1C7WRv,iv:tXkT5Re7a59CoF6/sXnt7/bmJtsbc3aA6hYkv0oOgLg=,tag:sO0ygzcDf7yfR751OM+HYg==,type:str]
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:qqYa9QL/xl8j0vz7Dkw555vwViZr,iv:uQ6BW1FKhIIM2iJsJYurvGE8X4S6aPX9P/C3756uQDI=,tag:EMw7i/cgAx2buJkPMrtglw==,type:str]
    R2_ACCESS_KEY_ID: ""
    R2_SECRET_ACCESS_KEY: ""
    OPENAI_API_KEY: ""
    OPENROUTER_API_KEY: ""
    GEMINI_API_KEY: ""
    TAVILY_API_KEY: ""
    SMTP_USER: ""
    SMTP_PASSWORD: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cn2x22y4xn5jflxe6539ujtc52m38tyjyfnv4nygva4wym7975kskt4smr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad09rcUViRE5jb2ZjR1Vk
            QlhrWGNkYXJDb0dFRXRWQWJTSG4rVEVJSXdJCkhkUENlTEVVVmN0OFlOZVRoN2dt
            dE9nOTliZCtuZURzVE52Rzg5ekZncG8KLS0tIEZJWFQ4Mjk2UXNYVkVEUjd4QnFu
            ZHB4MDNUZjFlSGRuOGtPalNiTnNIWGMKdcHoke1EUTW4ArypYdjofd29rHpt4D/L
            FYtW6wtwUTU5eWYLGH4+4bqZ+/7P+wJi6dLgrulvCY6P0f5WTSo/Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T12:18:31Z"
    mac: ENC[AES256_GCM,data:w5k/klYgNNLcoBAyYNXw/JiVXeHOmaj8jZjFyWEcQct/0+N1Ggfdj9F4vRB3QROUn0F9m/RED+6BAqbVQNYWaqGp4/8eeXsFRdPDYiFEgpRm+EaN7Kg2kYOSNjXHzKFJXAn/ktK4sw1UkvNKbjWtL6EkXa/Oe7P8/LUn0p78I1M=,iv:IeJhAdZoeMTyctBBhKS/9F2YRCz2vnaXn6dKk9jPtX4=,tag:AYsn+uaYxD4d86F7JzhLAg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
